# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['nautilus_trader',
 'nautilus_trader.accounting',
 'nautilus_trader.accounting.accounts',
 'nautilus_trader.adapters',
 'nautilus_trader.adapters._template',
 'nautilus_trader.adapters.betfair',
 'nautilus_trader.adapters.betfair.client',
 'nautilus_trader.adapters.betfair.parsing',
 'nautilus_trader.adapters.binance',
 'nautilus_trader.adapters.binance.common',
 'nautilus_trader.adapters.binance.common.schemas',
 'nautilus_trader.adapters.binance.futures',
 'nautilus_trader.adapters.binance.futures.http',
 'nautilus_trader.adapters.binance.futures.schemas',
 'nautilus_trader.adapters.binance.http',
 'nautilus_trader.adapters.binance.spot',
 'nautilus_trader.adapters.binance.spot.http',
 'nautilus_trader.adapters.binance.spot.schemas',
 'nautilus_trader.adapters.binance.websocket',
 'nautilus_trader.adapters.deribit',
 'nautilus_trader.adapters.deribit.http',
 'nautilus_trader.adapters.interactive_brokers',
 'nautilus_trader.adapters.interactive_brokers.parsing',
 'nautilus_trader.adapters.sandbox',
 'nautilus_trader.analysis',
 'nautilus_trader.analysis.statistics',
 'nautilus_trader.backtest',
 'nautilus_trader.cache',
 'nautilus_trader.common',
 'nautilus_trader.config',
 'nautilus_trader.core',
 'nautilus_trader.data',
 'nautilus_trader.examples',
 'nautilus_trader.examples.algorithms',
 'nautilus_trader.examples.strategies',
 'nautilus_trader.execution',
 'nautilus_trader.indicators',
 'nautilus_trader.indicators.average',
 'nautilus_trader.indicators.base',
 'nautilus_trader.indicators.fuzzy_enums',
 'nautilus_trader.infrastructure',
 'nautilus_trader.live',
 'nautilus_trader.model',
 'nautilus_trader.model.data',
 'nautilus_trader.model.events',
 'nautilus_trader.model.instruments',
 'nautilus_trader.model.orderbook',
 'nautilus_trader.model.orders',
 'nautilus_trader.model.tick_scheme',
 'nautilus_trader.model.tick_scheme.implementations',
 'nautilus_trader.msgbus',
 'nautilus_trader.network',
 'nautilus_trader.persistence',
 'nautilus_trader.persistence.catalog',
 'nautilus_trader.persistence.external',
 'nautilus_trader.persistence.streaming',
 'nautilus_trader.portfolio',
 'nautilus_trader.risk',
 'nautilus_trader.serialization',
 'nautilus_trader.serialization.arrow',
 'nautilus_trader.serialization.arrow.implementations',
 'nautilus_trader.serialization.msgpack',
 'nautilus_trader.system',
 'nautilus_trader.test_kit',
 'nautilus_trader.test_kit.mocks',
 'nautilus_trader.test_kit.stubs',
 'nautilus_trader.trading']

package_data = \
{'': ['*'],
 'nautilus_trader.core': ['includes/*',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/__init__.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/backtest.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pxd',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/common.pyx',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/core.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pxd',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/model.pyx',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd',
                          'rust/persistence_g.pxd']}

install_requires = \
['aiodns>=3.0.0,<4.0.0',
 'aiohttp>=3.8.4,<4.0.0',
 'click>=8.1.3,<9.0.0',
 'cython==3.0.0b2',
 'frozendict>=2.3.7,<3.0.0',
 'fsspec>=2022.5.0',
 'msgspec>=0.14.2,<0.15.0',
 'numpy>=1.24.3,<2.0.0',
 'pandas>=1.5.3,<2.0.0',
 'psutil>=5.9.5,<6.0.0',
 'pyarrow>=10.0.1,<11.0.0',
 'pytz>=2023.3.0,<2024.0.0',
 'tabulate>=0.9.0,<0.10.0',
 'toml>=0.10.2,<0.11.0',
 'tqdm>=4.65.0,<5.0.0']

extras_require = \
{':sys_platform != "win32"': ['uvloop>=0.17.0,<0.18.0'],
 'betfair': ['betfair_parser==0.1.21'],
 'docker': ['docker>=6.0.1,<7.0.0'],
 'ib': ['ib_insync>=0.9.82,<0.10.0'],
 'redis': ['hiredis>=2.2.2,<3.0.0', 'redis>=4.5.4,<5.0.0']}

setup_kwargs = {
    'name': 'nautilus-trader',
    'version': '1.172.0',
    'description': 'A high-performance algorithmic trading platform and event-driven backtester',
    'long_description': '# <img src="https://github.com/nautechsystems/nautilus_trader/blob/develop/docs/_images/nautilus-trader-logo.png" width="500">\n\n[![codacy-quality](https://api.codacy.com/project/badge/Grade/a1d3ccf7bccb4483b091975681a5cb23)](https://app.codacy.com/gh/nautechsystems/nautilus_trader?utm_source=github.com&utm_medium=referral&utm_content=nautechsystems/nautilus_trader&utm_campaign=Badge_Grade_Dashboard)\n[![codecov](https://codecov.io/gh/nautechsystems/nautilus_trader/branch/master/graph/badge.svg?token=DXO9QQI40H)](https://codecov.io/gh/nautechsystems/nautilus_trader)\n![pythons](https://img.shields.io/pypi/pyversions/nautilus_trader)\n![pypi-version](https://img.shields.io/pypi/v/nautilus_trader)\n![pypi-format](https://img.shields.io/pypi/format/nautilus_trader?color=blue)\n[![Downloads](https://pepy.tech/badge/nautilus-trader)](https://pepy.tech/project/nautilus-trader)\n[![discord](https://img.shields.io/discord/924497682343550976?color=768AD4&label=discord)](https://discord.gg/AUWVs3XaCS)\n\n| Branch    | Version | Status |\n|:----------|:--------|:-------|\n| `master`  | ![version](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnautechsystems%2Fnautilus_trader%2Fmaster%2Fversion.json) | [![build](https://github.com/nautechsystems/nautilus_trader/actions/workflows/build.yml/badge.svg?branch=master)](https://github.com/nautechsystems/nautilus_trader/actions/workflows/build.yml) |\n| `develop` | ![version](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnautechsystems%2Fnautilus_trader%2Fdevelop%2Fversion.json) | [![build](https://github.com/nautechsystems/nautilus_trader/actions/workflows/build.yml/badge.svg?branch=develop)](https://github.com/nautechsystems/nautilus_trader/actions/workflows/build.yml) |\n\n| Platform           | Rust    | Python |\n|:-------------------|:--------|:-------|\n| `Linux (x86_64)`   | 1.69.0+ | 3.9+   |\n| `macOS (x86_64)`   | 1.69.0+ | 3.9+   |\n| `Windows (x86_64)` | 1.69.0+ | 3.9+   |\n\n- **Website:** https://nautilustrader.io\n- **Docs:** https://docs.nautilustrader.io\n- **Support:** [support@nautilustrader.io](mailto:support@nautilustrader.io)\n\n## Introduction\n\nNautilusTrader is an open-source, high-performance, production-grade algorithmic trading platform,\nproviding quantitative traders with the ability to backtest portfolios of automated trading strategies\non historical data with an event-driven engine, and also deploy those same strategies live, with no code changes.\n\nThe platform is \'AI-first\', designed to develop and deploy algorithmic trading strategies within a highly performant \nand robust Python native environment. This helps to address the parity challenge of keeping the Python research/backtest \nenvironment, consistent with the production live trading environment.\n\nNautilusTraders design, architecture and implementation philosophy holds software correctness and safety at the\nhighest level, with the aim of supporting Python native, mission-critical, trading system backtesting\nand live deployment workloads.\n\nThe platform is also universal and asset class agnostic - with any REST, WebSocket or FIX API able to be integrated via modular\nadapters. Thus, it can handle high-frequency trading operations for any asset classes\nincluding FX, Equities, Futures, Options, CFDs, Crypto and Betting - across multiple venues simultaneously.\n\n## Features\n\n- **Fast** - C-level speed through Rust and Cython. Asynchronous networking with [uvloop](https://github.com/MagicStack/uvloop)\n- **Reliable** - Type safety through Rust and Cython. Redis backed performant state persistence\n- **Portable** - OS independent, runs on Linux, macOS, Windows. Deploy using Docker\n- **Flexible** - Modular adapters mean any REST, WebSocket, or FIX API can be integrated\n- **Advanced** - Time in force `IOC`, `FOK`, `GTD`, `AT_THE_OPEN`, `AT_THE_CLOSE`, advanced order types and conditional triggers. Execution instructions `post-only`, `reduce-only`, and icebergs. Contingency order lists including `OCO`, `OTO`\n- **Customizable** - Add user defined custom components, or assemble entire systems from scratch leveraging the cache and message bus\n- **Backtesting** - Run with multiple venues, instruments and strategies simultaneously using historical quote tick, trade tick, bar, order book and custom data with nanosecond resolution\n- **Live** - Use identical strategy implementations between backtesting and live deployments\n- **Multi-venue** - Multiple venue capabilities facilitate market making and statistical arbitrage strategies\n- **AI Agent Training** - Backtest engine fast enough to be used to train AI trading agents (RL/ES)\n\n![Alt text](https://github.com/nautechsystems/nautilus_trader/blob/develop/docs/_images/nautilus-art.png?raw=true "nautilus")\n> *nautilus - from ancient Greek \'sailor\' and naus \'ship\'.*\n>\n> *The nautilus shell consists of modular chambers with a growth factor which approximates a logarithmic spiral.\n> The idea is that this can be translated to the aesthetics of design and architecture.*\n\n## Why NautilusTrader?\n\n- **Highly performant event-driven Python** - native binary core components\n- **Parity between backtesting and live trading** - identical strategy code\n- **Reduced operational risk** - risk management functionality, logical correctness and type safety\n- **Highly extendable** - message bus, custom components and actors, custom data, custom adapters\n\nTraditionally, trading strategy research and backtesting might be conducted in Python (or other suitable language)\nusing vectorized methods, with the strategy then needing to be reimplemented in a more event-drive way\nusing C++, C#, Java or other statically typed language(s). The reasoning here is that vectorized backtesting code cannot\nexpress the granular time and event dependent complexity of real-time trading, where compiled languages have\nproven to be more suitable due to their inherently higher performance, and type safety.\n\nOne of the key advantages of NautilusTrader here, is that this reimplementation step is now circumvented - as the critical core components of the platform\nhave all been written entirely in Rust or Cython. This means we\'re using the right tools for the job, where systems programming languages compile performant binaries, \nwith CPython C extension modules then able to offer a Python native environment, suitable for professional quantitative traders and trading firms.\n\n## Why Python?\n\nPython was originally created decades ago as a simple scripting language with a clean straight\nforward syntax. It has since evolved into a fully fledged general purpose object-oriented\nprogramming language. Based on the TIOBE index, Python is currently the most popular programming language in the world.\nNot only that, Python has become the _de facto lingua franca_ of data science, machine learning, and artificial intelligence.\n\nThe language out of the box is not without its drawbacks however, especially in the context of\nimplementing large performance-critical systems. Cython has addressed a lot of these issues, offering all the advantages\nof a statically typed language, embedded into Pythons rich ecosystem of software libraries and\ndeveloper/user communities.\n\n## What is Cython?\n\n[Cython](https://cython.org) is a compiled programming language which aims to be a superset of the Python programming\nlanguage, designed to give C-like performance with code that is written in Python - with\noptional C-inspired syntax.\n\nThe project heavily utilizes Cython to provide static type safety and increased performance\nfor Python through [C extension modules](https://docs.python.org/3/extending/extending.html). The vast majority of the production code is actually\nwritten in Cython, however the libraries can be accessed from both Python and Cython.\n\n## What is Rust?\n\n[Rust](https://www.rust-lang.org/) is a multi-paradigm programming language designed for performance and safety, especially safe\nconcurrency. Rust is blazingly fast and memory-efficient (comparable to C and C++) with no runtime or\ngarbage collector. It can power mission-critical systems, run on embedded devices, and easily\nintegrates with other languages.\n\nRust’s rich type system and ownership model guarantees memory-safety and thread-safety deterministically —\neliminating many classes of bugs at compile-time.\n\nThe project increasingly utilizes Rust for core performance-critical components. Python language binding is handled through\nCython, with static libraries linked at compile-time before the wheel binaries are packaged, so a user\ndoes not need to have Rust installed to run NautilusTrader. In the future as more Rust code is introduced,\n[PyO3](https://pyo3.rs/latest) will be leveraged for easier Python bindings.\n\nThis project makes the [Soundness Pledge](https://raphlinus.github.io/rust/2020/01/18/soundness-pledge.html):\n> “The intent of this project is to be free of soundness bugs. \n> The developers will do their best to avoid them, and welcome help in analyzing and fixing them.”\n\n## Architecture (data flow)\n\n![Architecture](https://github.com/nautechsystems/nautilus_trader/blob/develop/docs/_images/architecture-overview.png?raw=true "architecture")\n\n## Quality Attributes\n\n- Reliability\n- Performance\n- Modularity\n- Testability\n- Maintainability\n- Deployability\n\n## Integrations\n\nNautilusTrader is designed in a modular way to work with \'adapters\' which provide\nconnectivity to data publishers and/or trading venues - converting their raw API\ninto a unified interface. The following integrations are currently supported:\n\n| Name                                                    | ID        | Type                    | Status                                              | Docs                                                              |\n|:--------------------------------------------------------|:----------|:------------------------|:----------------------------------------------------|:------------------------------------------------------------------|\n[Betfair](https://betfair.com)                            | `BETFAIR` | Sports Betting Exchange | ![status](https://img.shields.io/badge/beta-yellow) | [Guide](https://docs.nautilustrader.io/integrations/betfair.html) |\n[Binance](https://binance.com)                            | `BINANCE` | Crypto Exchange (CEX)   | ![status](https://img.shields.io/badge/beta-yellow) | [Guide](https://docs.nautilustrader.io/integrations/binance.html) |\n[Binance US](https://binance.us)                          | `BINANCE` | Crypto Exchange (CEX)   | ![status](https://img.shields.io/badge/beta-yellow) | [Guide](https://docs.nautilustrader.io/integrations/binance.html) |\n[Binance Futures](https://www.binance.com/en/futures)     | `BINANCE` | Crypto Exchange (CEX)   | ![status](https://img.shields.io/badge/beta-yellow) | [Guide](https://docs.nautilustrader.io/integrations/binance.html) |\n[Interactive Brokers](https://www.interactivebrokers.com) | `IB`      | Brokerage (multi-venue) | ![status](https://img.shields.io/badge/beta-yellow) | [Guide](https://docs.nautilustrader.io/integrations/ib.html)      |\n\nRefer to the [Integrations](https://docs.nautilustrader.io/integrations/index.html) documentation for further details.\n\n## Installation\n\n### From PyPI\n\nWe recommend running the platform with the latest stable version of Python, and in a virtual environment to isolate the dependencies.\n\nTo install the latest binary wheel from PyPI:\n\n    pip install -U nautilus_trader\n\n### From Source\nInstallation from source requires the `Python.h` header file, which is included in development releases such as `python-dev`.\nYou\'ll also need the latest stable `rustc` and `cargo` to compile the Rust libraries.\n\nFor MacBook Pro M1/M2, make sure your Python installed using pyenv is configured with `--enable-shared`:\n\n    PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install <python_version>\n\nSee https://pyo3.rs/latest/getting_started#virtualenvs.\n\nIt\'s possible to install from source using `pip` if you first install the build dependencies\nas specified in the `pyproject.toml`. However, we highly recommend installing using [poetry](https://python-poetry.org/) as below.\n\n1. Install [rustup](https://rustup.rs/) (the Rust toolchain installer):\n   - Linux and macOS:\n       ```\n       curl https://sh.rustup.rs -sSf | sh\n       ```\n   - Windows:\n       - Download and install [`rustup-init.exe`](https://win.rustup.rs/x86_64)\n       - Install "Desktop development with C++" with [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16)\n\n2. Enable `cargo` in the current shell:\n   - Linux and macOS:\n       ```\n       source $HOME/.cargo/env\n       ```\n   - Windows:\n     - Start a new PowerShell\n\n3. Install poetry (or follow the installation guide on their site):\n\n       curl -sSL https://install.python-poetry.org | python3 -\n\n4. Clone the source with `git`, and install from the projects root directory:\n\n       git clone https://github.com/nautechsystems/nautilus_trader\n       cd nautilus_trader\n       poetry install --only main --all-extras\n\nRefer to the [Installation Guide](https://docs.nautilustrader.io/getting_started/installation.html) for other options and further details.\n\n## Versioning and releases\n\nNautilusTrader is currently following a bi-weekly beta release schedule.\nThe API is becoming more stable, however breaking changes are still possible between releases.\nDocumentation of these changes in the release notes are made on a best-effort basis.\n\n### Branches\n- `master` branch will always reflect the source code for the latest released version\n- `develop` branch is normally very active with frequent commits and may contain experimental features. We aim to maintain a stable \npassing build on this branch\n\nThe current roadmap has a goal of achieving a stable API for a `2.x` version. From this\npoint we will follow a formal process for releases, with deprecation periods for any API changes.\n\n## Makefile\n\nA `Makefile` is provided to automate most installation and build tasks for development. It provides the following targets:\n- `make install` -- Installs in `release` build mode with `main`, `dev` and `test` dependencies then installs the package using poetry (default)\n- `make install-debug` -- Same as `make install` but with `debug` build mode\n- `make install-just-deps` -- Installs just the `main`, `dev` and `test` dependencies (does not install package)\n- `make install-just-deps-all` -- Same as `make install-just-deps` and additionally installs `docs` dependencies\n- `make build` -- Runs the Cython build script in `release` build mode (default)\n- `make build-debug` -- Runs the Cython build script in `debug` build mode\n- `make clean` -- **CAUTION** Cleans all non-source artifacts from the repository\n- `make docs` -- Builds the documentation HTML using Sphinx\n- `make pre-commit` -- Runs the pre-commit checks over all files\n- `make ruff` -- Runs ruff over all files using the `pyproject.toml` config\n- `make pytest` -- Runs all tests with `pytest` (except performance tests)\n- `make pytest-coverage` -- Same as `make pytest` and additionally runs with test coverage and produces a report\n\n## Examples\n\nIndicators and strategies can be developed in both Python and Cython (although if performance and latency sensitivity are import we recommend Cython).\nThe below are some examples of this:\n- [indicator](/examples/indicators/ema_python.py) example written in Python\n- [indicator](/nautilus_trader/indicators/) examples written in Cython\n- [strategy](/nautilus_trader/examples/strategies/) examples written in both Python and Cython\n- [backtest](/examples/backtest/) examples using a `BacktestEngine` directly\n\n## Docker\n\nDocker containers are built using a base `python:3.10-slim` with the following image variant tags:\n- `nautilus_trader:latest` has the latest release version installed\n- `nautilus_trader:develop` has the head of the `develop` branch installed\n- `jupyterlab:develop` has the head of the `develop` branch installed along with `jupyterlab` and an\nexample backtest notebook with accompanying data\n\nThe container images can be pulled as follows:\n\n    docker pull ghcr.io/nautechsystems/<image_variant_tag>\n\nYou can launch the backtest example container by running:\n\n    docker pull ghcr.io/nautechsystems/jupyterlab:develop\n    docker run -p 8888:8888 ghcr.io/nautechsystems/jupyterlab:develop\n\n| :warning: WARNING                                                               |\n|:--------------------------------------------------------------------------------|\n\n**NautilusTrader currently exceeds the rate limit for Jupyter notebook logging (stdout output),\nthis is why `log_level` in the examples is set to "ERROR". If you lower this level to see more\nlogging then the notebook will hang during cell execution. A fix is currently\nbeing investigated which involves either raising the configured rate limits for\nJupyter, or throttling the log flushing from Nautilus.**\nhttps://github.com/jupyterlab/jupyterlab/issues/12845\nhttps://github.com/deshaw/jupyterlab-limit-output\n\n## Minimal Strategy\n\nThe following is a minimal EMA Cross strategy example which just uses bar data.\nWhile trading strategies can become very advanced with this platform, it\'s still possible to put\ntogether simple strategies. First inherit from the `Strategy` base class, then only the\nmethods which are required by the strategy need to be implemented.\n\n```python\nclass EMACross(Strategy):\n    """\n    A simple moving average cross example strategy.\n\n    When the fast EMA crosses the slow EMA then enter a position at the market\n    in that direction.\n\n    Cancels all orders and closes all positions on stop.\n    """\n\n    def __init__(self, config: EMACrossConfig) -> None:\n        super().__init__(config)\n\n        # Configuration\n        self.instrument_id = InstrumentId.from_str(config.instrument_id)\n        self.bar_type = BarType.from_str(config.bar_type)\n        self.trade_size = Decimal(config.trade_size)\n\n        # Create the indicators for the strategy\n        self.fast_ema = ExponentialMovingAverage(config.fast_ema_period)\n        self.slow_ema = ExponentialMovingAverage(config.slow_ema_period)\n\n        self.instrument: Optional[Instrument] = None  # Initialized in on_start\n\n    def on_start(self) -> None:\n        """Actions to be performed on strategy start."""\n        # Get instrument\n        self.instrument = self.cache.instrument(self.instrument_id)\n\n        # Register the indicators for updating\n        self.register_indicator_for_bars(self.bar_type, self.fast_ema)\n        self.register_indicator_for_bars(self.bar_type, self.slow_ema)\n\n        # Get historical data\n        self.request_bars(self.bar_type)\n\n        # Subscribe to live data\n        self.subscribe_bars(self.bar_type)\n\n    def on_bar(self, bar: Bar) -> None:\n        """Actions to be performed when the strategy receives a bar."""\n        # BUY LOGIC\n        if self.fast_ema.value >= self.slow_ema.value:\n            if self.portfolio.is_flat(self.instrument_id):\n                self.buy()\n            elif self.portfolio.is_net_short(self.instrument_id):\n                self.close_all_positions(self.instrument_id)\n                self.buy()\n        # SELL LOGIC\n        elif self.fast_ema.value < self.slow_ema.value:\n            if self.portfolio.is_flat(self.instrument_id):\n                self.sell()\n            elif self.portfolio.is_net_long(self.instrument_id):\n                self.close_all_positions(self.instrument_id)\n                self.sell()\n\n    def buy(self) -> None:\n        """Users simple buy method (example)."""\n        order: MarketOrder = self.order_factory.market(\n            instrument_id=self.instrument_id,\n            order_side=OrderSide.BUY,\n            quantity=self.instrument.make_qty(self.trade_size),\n        )\n\n        self.submit_order(order)\n\n    def sell(self) -> None:\n        """Users simple sell method (example)."""\n        order: MarketOrder = self.order_factory.market(\n            instrument_id=self.instrument_id,\n            order_side=OrderSide.SELL,\n            quantity=self.instrument.make_qty(self.trade_size),\n        )\n\n        self.submit_order(order)\n\n    def on_stop(self) -> None:\n        """Actions to be performed when the strategy is stopped."""\n        # Cleanup orders and positions\n        self.cancel_all_orders(self.instrument_id)\n        self.close_all_positions(self.instrument_id)\n\n        # Unsubscribe from data\n        self.unsubscribe_bars(self.bar_type)\n\n    def on_reset(self) -> None:\n        """Actions to be performed when the strategy is reset."""\n        # Reset indicators here\n        self.fast_ema.reset()\n        self.slow_ema.reset()\n\n```\n\n## Development\n\nWe aim to provide the most pleasant developer experience possible for this hybrid codebase of Python, Cython and Rust.\nRefer to the [Developer Guide](https://docs.nautilustrader.io/developer_guide/index.html) for helpful information.\n\n## Contributing\n\nThank you for considering contributing to Nautilus Trader! We welcome any and all help to improve \nthe project. If you have an idea for an enhancement or a bug fix, the first step is to open an [issue](https://github.com/nautechsystems/nautilus_trader/issues) \non GitHub to discuss it with the team. This helps to ensure that your contribution will be \nwell-aligned with the goals of the project and avoids duplication of effort.\n\nOnce you\'re ready to start working on your contribution, make sure to follow the guidelines \noutlined in the [CONTRIBUTING.md](https://github.com/nautechsystems/nautilus_trader/blob/develop/CONTRIBUTING.md) file. This includes signing a Contributor License Agreement (CLA) \nto ensure that your contributions can be included in the project.\n\nNote that all pull requests should be made to the `develop` branch. This is where new features \nand improvements are integrated before being released to the public.\n\nThank you again for your interest in Nautilus Trader! We look forward to reviewing your contributions and working with you to improve the project.\n\n## Community\nJoin our community of users and contributors on [Discord](https://discord.gg/AUWVs3XaCS) to chat \nand stay up-to-date with the latest announcements and features of NautilusTrader. Whether you\'re a \ndeveloper looking to contribute or just want to learn more about the platform, all are welcome on our server.\n\n## License\n\nThe source code for NautilusTrader is available on GitHub under the [GNU Lesser General Public License v3.0](https://www.gnu.org/licenses/lgpl-3.0.en.html).\nContributions to the project are welcome and require the completion of a standard Contributor License Agreement (CLA).\n\n---\n\nNautilusTrader is developed and maintained by Nautech Systems, a technology \ncompany specializing in the development of high-performance trading systems. \nAlthough the project utilizes the Rust programming language and benefits from its ecosystem, \nNautech Systems is not affiliated with the Rust Foundation, and this project is not an official \nwork of the Rust Foundation.\nFor more information, visit https://nautilustrader.io.\n\nCopyright (C) 2015-2023 Nautech Systems Pty Ltd. All rights reserved.\n\n![nautechsystems](https://github.com/nautechsystems/nautilus_trader/blob/develop/docs/_images/ns-logo.png?raw=true "nautechsystems")\n<img src="https://github.com/nautechsystems/nautilus_trader/blob/develop/docs/_images/ferris.png" width="128">\n',
    'author': 'Nautech Systems',
    'author_email': 'info@nautechsystems.io',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://nautilustrader.io',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'python_requires': '>=3.9,<3.12',
}
# from build import *
# build()

setup(**setup_kwargs)
