[package]
name = "nautilus_persistence"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "nautilus_persistence"
crate-type = ["rlib", "staticlib", "cdylib" ]

[dependencies]
nautilus_core = { path = "../core" }
nautilus_model = { path = "../model" }
chrono.workspace = true
pyo3.workspace = true
rand.workspace = true
once_cell = "1.17.0"
arrow2 = { version = "0.15.0", features = [ "io_parquet", "io_csv_read", "compute_comparison" ] }
datafusion = "17.0.0"
tokio = "1.25.0"
futures = "0.3.26"
pyo3-asyncio = { version = "0.18.0", features = [ "tokio-runtime", "tokio", "attributes" ] }
stream-kmerge = "0.2.0"

[features]
extension-module = ["pyo3/extension-module", "nautilus_core/extension-module", "nautilus_model/extension-module"]
default = []
