# Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

from libc.stdint cimport uintptr_t
from nautilus_trader.core.rust.core cimport CVec
from nautilus_trader.core.rust.model cimport QuoteTick_t

cdef extern from "../includes/persistence_g.h":

    void *parquet_reader_new(const char *file_path, uintptr_t chunk_size);

    CVec parquet_reader_next_chunk(void *reader);

    void parquet_reader_drop_chunk(CVec chunk);

    void parquet_reader_free(void *reader);
