/* Generated with cbindgen:0.24.5 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <Python.h>

typedef struct Vec_QuoteTick {
    QuoteTick_t *ptr;
    uintptr_t cap;
    uintptr_t len;
} Vec_QuoteTick;

void *parquet_reader_new(const char *file_path, uintptr_t chunk_size);

struct Vec_QuoteTick *parquet_reader_next_chunk(void *reader);

void free_chunk(struct Vec_QuoteTick *data);
