/* Generated with cbindgen:0.24.5 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <Python.h>

void *parquet_reader_new(const char *file_path, uintptr_t chunk_size);

CVec parquet_reader_next_chunk(void *reader);

void parquet_reader_drop_chunk(CVec chunk);

void parquet_reader_free(void *reader);
