/* Generated with cbindgen:0.24.5 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <Python.h>

void *parquet_reader_new(const char *file_path, uintptr_t chunk_size);

QuoteTick_t quote_tick_clone(const QuoteTick_t *data);

CVec parquet_reader_next_chunk(void *reader);

void parquet_reader_drop_chunk(CVec chunk);

/**
 * # Safety
 * - Assumes `reader` is a valid `*mut ParquetReader<Struct>` where the struct
 * has a corresponding [ParquetType] enum.
 */
void parquet_reader_free(void *reader);
